# Remember to update the version in the pyproject.toml.
repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8