name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
    name: Test - ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get Poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.1.12
      - name: Install
        run: poetry install
      - name: Run tests
        run: poetry run pytest tests.py
